USE [portalia]
GO
/****** Object:  Table [dbo].[Currency]    Script Date: 1/10/2017 2:26:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Currency](
	[ID] [varchar](3) NOT NULL,
	[Label] [varchar](128) NOT NULL,
	[Disabled] [bit] NOT NULL CONSTRAINT [DF__Currency__Disabl__1DF12CC8]  DEFAULT ((0)),
	[Counter] [int] NOT NULL CONSTRAINT [DF__Currency__Counte__1EE55101]  DEFAULT ((0)),
	[Created_Date] [datetime] NOT NULL CONSTRAINT [DF__Currency__Create__1FD9753A]  DEFAULT (getdate()),
	[Updated_Date] [datetime] NULL,
	[Symbol] [nvarchar](5) NULL,
 CONSTRAINT [PK_Currency] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AED', N'United Arab Emirates dirham', 0, 0, CAST(N'2013-02-07 13:17:12.653' AS DateTime), NULL, N'د.إ')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AFN', N'Afghan afghani', 0, 0, CAST(N'2013-02-07 13:17:12.657' AS DateTime), NULL, N'؋')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ALL', N'Albanian lek', 0, 0, CAST(N'2013-02-07 13:17:12.660' AS DateTime), NULL, N'Lek')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AMD', N'Armenian dram', 0, 0, CAST(N'2013-02-07 13:17:12.700' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ANG', N'Netherlands Antillean guilder', 0, 0, CAST(N'2013-02-07 13:17:12.717' AS DateTime), NULL, N'ƒ')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AOA', N'Angolan kwanza', 0, 0, CAST(N'2013-02-07 13:17:12.720' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ARS', N'Argentine peso', 0, 0, CAST(N'2013-02-07 13:17:12.723' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AUD', N'Australian dollar', 0, 0, CAST(N'2013-02-07 13:17:12.727' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AWG', N'Aruban florin', 0, 0, CAST(N'2013-02-07 13:17:12.747' AS DateTime), NULL, N'ƒ')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'AZN', N'Azerbaijani manat', 0, 0, CAST(N'2013-02-07 13:17:12.750' AS DateTime), NULL, N'ман')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BAM', N'Bosnia and Herzegovina convertible mark', 0, 0, CAST(N'2013-02-07 13:17:12.753' AS DateTime), NULL, N'KM')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BBD', N'Barbados dollar', 0, 0, CAST(N'2013-02-07 13:17:12.757' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BDT', N'Bangladeshi taka', 0, 0, CAST(N'2013-02-07 13:17:12.760' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BGN', N'Bulgarian lev', 0, 0, CAST(N'2013-02-07 13:17:12.780' AS DateTime), NULL, N'лв')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BHD', N'Bahraini dinar', 0, 0, CAST(N'2013-02-07 13:17:12.783' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BIF', N'Burundian franc', 0, 0, CAST(N'2013-02-07 13:17:12.790' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BMD', N'Bermudian dollar', 0, 0, CAST(N'2013-02-07 13:17:12.793' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BND', N'Brunei dollar', 0, 0, CAST(N'2013-02-07 13:17:12.797' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BOB', N'Boliviano', 0, 0, CAST(N'2013-02-07 13:17:12.803' AS DateTime), NULL, N'$b')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BOV', N'Bolivian Mvdol', 0, 0, CAST(N'2013-02-07 13:17:12.827' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BRL', N'Brazilian real', 0, 0, CAST(N'2013-02-07 13:17:12.830' AS DateTime), NULL, N'R$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BSD', N'Bahamian dollar', 0, 0, CAST(N'2013-02-07 13:17:12.837' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BTN', N'Bhutanese ngultrum', 0, 0, CAST(N'2013-02-07 13:17:12.840' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BWP', N'Botswana pula', 0, 0, CAST(N'2013-02-07 13:17:12.847' AS DateTime), NULL, N'P')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BYR', N'Belarusian ruble', 0, 0, CAST(N'2013-02-07 13:17:12.850' AS DateTime), NULL, N'p.')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'BZD', N'Belize dollar', 0, 0, CAST(N'2013-02-07 13:17:12.857' AS DateTime), NULL, N'BZ$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CAD', N'Canadian dollar', 0, 0, CAST(N'2013-02-07 13:17:12.883' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CDF', N'Congolese franc', 0, 0, CAST(N'2013-02-07 13:17:12.890' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CHE', N'WIR Euro', 0, 0, CAST(N'2013-02-07 13:17:12.893' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CHF', N'Swiss Franc', 0, 0, CAST(N'2010-05-04 15:52:11.237' AS DateTime), NULL, N'CHF')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CHW', N'WIR Franc', 0, 0, CAST(N'2013-02-07 13:17:12.907' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CLF', N'Unidad de Fomento', 0, 0, CAST(N'2013-02-07 13:17:12.910' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CLP', N'Chilean peso', 0, 0, CAST(N'2013-02-07 13:17:12.917' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CNY', N'Chinese yuan', 0, 0, CAST(N'2013-02-07 13:17:12.923' AS DateTime), NULL, N'¥')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'COP', N'Colombian peso', 0, 0, CAST(N'2013-02-07 13:17:12.957' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'COU', N'Unidad de Valor Real', 0, 0, CAST(N'2013-02-07 13:17:12.963' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CRC', N'Costa Rican colon', 0, 0, CAST(N'2013-02-07 13:17:12.970' AS DateTime), NULL, N'₡')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CUC', N'Cuban convertible peso', 0, 0, CAST(N'2013-02-07 13:17:12.973' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CUP', N'Cuban peso', 0, 0, CAST(N'2013-02-07 13:17:12.980' AS DateTime), NULL, N'₱')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CVE', N'Cape Verde escudo', 0, 0, CAST(N'2013-02-07 13:17:12.987' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'CZK', N'Czech Koruna', 0, 0, CAST(N'2012-03-19 09:53:15.900' AS DateTime), NULL, N'Kč')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'DJF', N'Djiboutian franc', 0, 0, CAST(N'2013-02-07 13:17:13.000' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'DKK', N'Danish krone', 0, 0, CAST(N'2013-02-07 13:17:13.003' AS DateTime), NULL, N'kr')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'DOP', N'Dominican peso', 0, 0, CAST(N'2013-02-07 13:17:13.010' AS DateTime), NULL, N'RD$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'DZD', N'Algerian dinar', 0, 0, CAST(N'2013-02-07 13:17:13.050' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'EGP', N'Egyptian pound', 0, 0, CAST(N'2013-02-07 13:17:13.057' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ERN', N'Eritrean nakfa', 0, 0, CAST(N'2013-02-07 13:17:13.063' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ETB', N'Ethiopian birr', 0, 0, CAST(N'2013-02-07 13:17:13.073' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'EUR', N'Euro', 0, 0, CAST(N'2010-05-04 15:52:11.237' AS DateTime), NULL, N'€')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'FJD', N'Fiji dollar', 0, 0, CAST(N'2013-02-07 13:17:13.087' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'FKP', N'Falkland Islands pound', 0, 0, CAST(N'2013-02-07 13:17:13.093' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GBP', N'Pound sterling', 0, 0, CAST(N'2010-06-04 13:11:42.793' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GEL', N'Georgian lari', 0, 0, CAST(N'2013-02-07 13:17:13.110' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GHS', N'Ghanaian cedi', 0, 0, CAST(N'2013-02-07 13:17:13.117' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GIP', N'Gibraltar pound', 0, 0, CAST(N'2013-02-07 13:17:13.123' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GMD', N'Gambian dalasi', 0, 0, CAST(N'2013-02-07 13:17:13.130' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GNF', N'Guinean franc', 0, 0, CAST(N'2013-02-07 13:17:13.177' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GTQ', N'Guatemalan quetzal', 0, 0, CAST(N'2013-02-07 13:17:13.180' AS DateTime), NULL, N'Q')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'GYD', N'Guyanese dollar', 0, 0, CAST(N'2013-02-07 13:17:13.187' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'HKD', N'Hong Kong dollar', 0, 0, CAST(N'2013-02-07 13:17:13.190' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'HNL', N'Honduran lempira', 0, 0, CAST(N'2013-02-07 13:17:13.197' AS DateTime), NULL, N'L')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'HRK', N'Croatian kuna', 0, 0, CAST(N'2013-02-07 13:17:13.200' AS DateTime), NULL, N'kn')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'HTG', N'Haitian gourde', 0, 0, CAST(N'2013-02-07 13:17:13.203' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'HUF', N'Hungarian forint', 0, 0, CAST(N'2013-02-07 13:17:13.210' AS DateTime), NULL, N'Ft')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'IDR', N'Indonesian rupiah', 0, 0, CAST(N'2013-02-07 13:17:13.213' AS DateTime), NULL, N'Rp')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ILS', N'Israeli new shekel', 0, 0, CAST(N'2013-02-07 13:17:13.220' AS DateTime), NULL, N'₪')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'INR', N'Indian Rupee', 0, 0, CAST(N'2012-03-26 19:04:23.013' AS DateTime), NULL, N'र')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'IQD', N'Iraqi dinar', 0, 0, CAST(N'2013-02-07 13:17:13.230' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'IRR', N'Iranian rial', 0, 0, CAST(N'2013-02-07 13:17:13.233' AS DateTime), NULL, N'﷼')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ISK', N'Icelandic króna', 0, 0, CAST(N'2013-02-07 13:17:13.240' AS DateTime), NULL, N'kr')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'JMD', N'Jamaican dollar', 0, 0, CAST(N'2013-02-07 13:17:13.297' AS DateTime), NULL, N'J$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'JOD', N'Jordanian dinar', 0, 0, CAST(N'2013-02-07 13:17:13.303' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'JPY', N'Japanese yen', 0, 0, CAST(N'2013-02-07 13:17:13.307' AS DateTime), NULL, N'¥')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KES', N'Kenyan shilling', 0, 0, CAST(N'2013-02-07 13:17:13.313' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KGS', N'Kyrgyzstani som', 0, 0, CAST(N'2013-02-07 13:17:13.317' AS DateTime), NULL, N'лв')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KHR', N'Cambodian riel', 0, 0, CAST(N'2013-02-07 13:17:13.323' AS DateTime), NULL, N'៛')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KMF', N'Comoro franc', 0, 0, CAST(N'2013-02-07 13:17:13.330' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KPW', N'North Korean won', 0, 0, CAST(N'2013-02-07 13:17:13.333' AS DateTime), NULL, N'₩')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KRW', N'South Korean won', 0, 0, CAST(N'2013-02-07 13:17:13.340' AS DateTime), NULL, N'₩')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KWD', N'Kuwaiti dinar', 0, 0, CAST(N'2013-02-07 13:17:13.343' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KYD', N'Cayman Islands dollar', 0, 0, CAST(N'2013-02-07 13:17:13.350' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'KZT', N'Kazakhstani tenge', 0, 0, CAST(N'2013-02-07 13:17:13.353' AS DateTime), NULL, N'лв')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LAK', N'Lao kip', 0, 0, CAST(N'2013-02-07 13:17:13.360' AS DateTime), NULL, N'₭')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LBP', N'Lebanese pound', 0, 0, CAST(N'2013-02-07 13:17:13.367' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LKR', N'Sri Lankan rupee', 0, 0, CAST(N'2013-02-07 13:17:13.370' AS DateTime), NULL, N'₨')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LRD', N'Liberian dollar', 0, 0, CAST(N'2013-02-07 13:17:13.377' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LSL', N'Lesotho loti', 0, 0, CAST(N'2013-02-07 13:17:13.383' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LTL', N'Lithuanian litas', 0, 0, CAST(N'2013-02-07 13:17:13.447' AS DateTime), NULL, N'Lt')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LVL', N'Latvian lats', 0, 0, CAST(N'2013-02-07 13:17:13.453' AS DateTime), NULL, N'Ls')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'LYD', N'Libyan dinar', 0, 0, CAST(N'2013-02-07 13:17:13.460' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MAD', N'Moroccan dirham', 0, 0, CAST(N'2013-02-07 13:17:13.463' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MDL', N'Moldovan leu', 0, 0, CAST(N'2013-02-07 13:17:13.470' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MGA', N'Malagasy ariary', 0, 0, CAST(N'2013-02-07 13:17:13.477' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MKD', N'Macedonian denar', 0, 0, CAST(N'2013-02-07 13:17:13.480' AS DateTime), NULL, N'ден')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MMK', N'Myanma kyat', 0, 0, CAST(N'2013-02-07 13:17:13.487' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MNT', N'Mongolian tugrik', 0, 0, CAST(N'2013-02-07 13:17:13.493' AS DateTime), NULL, N'₮')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MOP', N'Macanese pataca', 0, 0, CAST(N'2013-02-07 13:17:13.500' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MRO', N'Mauritanian ouguiya', 0, 0, CAST(N'2013-02-07 13:17:13.503' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MUR', N'Mauritian rupee', 0, 0, CAST(N'2013-02-07 13:17:13.510' AS DateTime), NULL, N'₨')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MVR', N'Maldivian rufiyaa', 0, 0, CAST(N'2013-02-07 13:17:13.517' AS DateTime), NULL, NULL)
GO
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MWK', N'Malawian kwacha', 0, 0, CAST(N'2013-02-07 13:17:13.520' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MXN', N'Mexican Peso', 0, 0, CAST(N'2010-06-04 13:11:42.793' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MXV', N'Mexican Unidad de Inversion (UDI) ', 0, 0, CAST(N'2013-02-07 13:17:13.533' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MYR', N'Malaysian ringgit', 0, 0, CAST(N'2013-02-07 13:17:13.540' AS DateTime), NULL, N'RM')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'MZN', N'Mozambican metical', 0, 0, CAST(N'2013-02-07 13:17:13.543' AS DateTime), NULL, N'MT')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NAD', N'Namibian dollar', 0, 0, CAST(N'2013-02-07 13:17:13.550' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NGN', N'Nigerian naira', 0, 0, CAST(N'2013-02-07 13:17:13.557' AS DateTime), NULL, N'₦')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NIO', N'Nicaraguan córdoba', 0, 0, CAST(N'2013-02-07 13:17:13.630' AS DateTime), NULL, N'C$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NOK', N'Norwegian krone', 0, 0, CAST(N'2013-02-07 13:17:13.637' AS DateTime), NULL, N'kr')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NPR', N'Nepalese rupee', 0, 0, CAST(N'2013-02-07 13:17:13.643' AS DateTime), NULL, N'₨')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'NZD', N'New Zealand dollar', 0, 0, CAST(N'2013-02-07 13:17:13.650' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'OMR', N'Omani rial', 0, 0, CAST(N'2013-02-07 13:17:13.653' AS DateTime), NULL, N'﷼')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PAB', N'Panamanian balboa', 0, 0, CAST(N'2013-02-07 13:17:13.660' AS DateTime), NULL, N'B/.')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PEN', N'Peruvian nuevo sol', 0, 0, CAST(N'2013-02-07 13:17:13.667' AS DateTime), NULL, N'S/.')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PGK', N'Papua New Guinean kina', 0, 0, CAST(N'2013-02-07 13:17:13.673' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PHP', N'Philippine peso', 0, 0, CAST(N'2013-02-07 13:17:13.680' AS DateTime), NULL, N'₱')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PKR', N'Pakistani rupee', 0, 0, CAST(N'2013-02-07 13:17:13.687' AS DateTime), NULL, N'₨')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PLN', N'Polish zloty', 0, 0, CAST(N'2013-02-07 13:17:13.690' AS DateTime), NULL, N'zł')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'PYG', N'Paraguayan guaraní', 0, 0, CAST(N'2013-02-07 13:17:13.700' AS DateTime), NULL, N'Gs')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'QAR', N'Qatari riyal', 0, 0, CAST(N'2013-02-07 13:17:13.703' AS DateTime), NULL, N'﷼')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'RON', N'Romanian new leu', 0, 0, CAST(N'2013-02-07 13:17:13.710' AS DateTime), NULL, N'lei')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'RSD', N'Serbian dinar', 0, 0, CAST(N'2013-02-07 13:17:13.717' AS DateTime), NULL, N'Дин.')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'RUB', N'Russian rouble', 0, 0, CAST(N'2013-02-07 13:17:13.723' AS DateTime), NULL, N'руб')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'RWF', N'Rwandan franc', 0, 0, CAST(N'2013-02-07 13:17:13.730' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SAR', N'Saudi riyal', 0, 0, CAST(N'2013-02-07 13:17:13.737' AS DateTime), NULL, N'﷼')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SBD', N'Solomon Islands dollar', 0, 0, CAST(N'2013-02-07 13:17:13.743' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SCR', N'Seychelles rupee', 0, 0, CAST(N'2013-02-07 13:17:13.750' AS DateTime), NULL, N'₨')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SDG', N'Sudanese pound', 0, 0, CAST(N'2013-02-07 13:17:13.757' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SEK', N'Swedish krona/kronor', 0, 0, CAST(N'2013-02-07 13:17:13.763' AS DateTime), NULL, N'kr')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SGD', N'Singapore dollar', 0, 0, CAST(N'2012-03-19 08:02:03.947' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SHP', N'Saint Helena pound', 0, 0, CAST(N'2013-02-07 13:17:13.777' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SLL', N'Sierra Leonean leone', 0, 0, CAST(N'2013-02-07 13:17:13.867' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SOS', N'Somali shilling', 0, 0, CAST(N'2013-02-07 13:17:13.873' AS DateTime), NULL, N'S')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SRD', N'Surinamese dollar', 0, 0, CAST(N'2013-02-07 13:17:13.880' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SSP', N'South Sudanese pound', 0, 0, CAST(N'2013-02-07 13:17:13.887' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'STD', N'São Tomé and Príncipe dobra', 0, 0, CAST(N'2013-02-07 13:17:13.893' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SYP', N'Syrian pound', 0, 0, CAST(N'2013-02-07 13:17:13.900' AS DateTime), NULL, N'£')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'SZL', N'Swazi lilangeni', 0, 0, CAST(N'2013-02-07 13:17:13.917' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'THB', N'Thai baht', 0, 0, CAST(N'2013-02-07 13:17:13.933' AS DateTime), NULL, N'฿')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TJS', N'Tajikistani somoni', 0, 0, CAST(N'2013-02-07 13:17:13.950' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TMT', N'Turkmenistani manat', 0, 0, CAST(N'2013-02-07 13:17:13.970' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TND', N'Tunisian dinar', 0, 0, CAST(N'2013-02-07 13:17:13.987' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TOP', N'Tongan pa?anga', 0, 0, CAST(N'2013-02-07 13:17:14.003' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TRY', N'Turkish lira', 0, 0, CAST(N'2013-02-07 13:17:14.020' AS DateTime), NULL, N'')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TTD', N'Trinidad and Tobago dollar', 0, 0, CAST(N'2013-02-07 13:17:14.040' AS DateTime), NULL, N'TT$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TWD', N'New Taiwan dollar', 0, 0, CAST(N'2013-02-07 13:17:14.057' AS DateTime), NULL, N'NT$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'TZS', N'Tanzanian shilling', 0, 0, CAST(N'2013-02-07 13:17:14.073' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'UAH', N'Ukrainian hryvnia', 0, 0, CAST(N'2013-02-07 13:17:14.090' AS DateTime), NULL, N'₴')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'UGX', N'Ugandan shilling', 0, 0, CAST(N'2013-02-07 13:17:14.107' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'USD', N'United States Dollars', 0, 0, CAST(N'2010-05-04 15:52:11.237' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'USN', N'United States dollar (next day)', 0, 0, CAST(N'2013-02-07 13:17:14.140' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'USS', N'United States dollar (same day)', 0, 0, CAST(N'2013-02-07 13:17:14.160' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'UYI', N'Uruguay Peso en Unidades Indexadas (URUIURUI)', 0, 0, CAST(N'2013-02-07 13:17:14.177' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'UYU', N'Uruguayan peso', 0, 0, CAST(N'2013-02-07 13:17:14.197' AS DateTime), NULL, N'$U')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'UZS', N'Uzbekistan som', 0, 0, CAST(N'2013-02-07 13:17:14.213' AS DateTime), NULL, N'лв')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'VEF', N'Venezuelan bolívar fuerte', 0, 0, CAST(N'2013-02-07 13:17:14.230' AS DateTime), NULL, N'Bs')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'VND', N'Vietnamese dong', 0, 0, CAST(N'2013-02-07 13:17:14.250' AS DateTime), NULL, N'₫')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'VUV', N'Vanuatu vatu', 0, 0, CAST(N'2013-02-07 13:17:14.267' AS DateTime), NULL, N'₫')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'WST', N'Samoan tala', 0, 0, CAST(N'2013-02-07 13:17:14.283' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XAF', N'CFA franc BEAC', 0, 0, CAST(N'2013-02-07 13:17:14.300' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XAG', N'Silver', 0, 0, CAST(N'2013-02-07 13:17:14.410' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XAU', N'Gold', 0, 0, CAST(N'2013-02-07 13:17:14.427' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XBA', N'European Composite Unit (EURCO)', 0, 0, CAST(N'2013-02-07 13:17:14.443' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XBB', N'European Monetary Unit (E.M.U.-6)', 0, 0, CAST(N'2013-02-07 13:17:14.460' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XBC', N'European Unit of Account 9 (E.U.A.-9)', 0, 0, CAST(N'2013-02-07 13:17:14.480' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XBD', N'European Unit of Account 17 (E.U.A.-17)', 0, 0, CAST(N'2013-02-07 13:17:14.497' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XCD', N'East Caribbean dollar', 0, 0, CAST(N'2013-02-07 13:17:14.517' AS DateTime), NULL, N'$')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XDR', N'Special drawing rights', 0, 0, CAST(N'2013-02-07 13:17:14.537' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XFU', N'UIC franc', 0, 0, CAST(N'2013-02-07 13:17:14.553' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XOF', N'CFA franc BCEAO', 0, 0, CAST(N'2013-02-07 13:17:14.573' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XPD', N'Palladium', 0, 0, CAST(N'2013-02-07 13:17:14.590' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XPF', N'CFP franc', 0, 0, CAST(N'2013-02-07 13:17:14.610' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XPT', N'Platinum', 0, 0, CAST(N'2013-02-07 13:17:14.627' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XTS', N'Code reserved for testing purposes', 0, 0, CAST(N'2013-02-07 13:17:14.647' AS DateTime), NULL, NULL)
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'XXX', N'No currency', 0, 0, CAST(N'2013-02-07 13:17:14.663' AS DateTime), NULL, N'₫')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'YER', N'Yemeni rial', 0, 0, CAST(N'2013-02-07 13:17:14.680' AS DateTime), NULL, N'﷼')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ZAR', N'South African rand', 0, 0, CAST(N'2013-02-07 13:17:14.700' AS DateTime), NULL, N'R')
INSERT [dbo].[Currency] ([ID], [Label], [Disabled], [Counter], [Created_Date], [Updated_Date], [Symbol]) VALUES (N'ZMW', N'Zambian kwacha', 0, 0, CAST(N'2013-02-07 13:17:14.717' AS DateTime), NULL, NULL)
