USE [Portalia]

alter table [dbo].[CountryLanguage] drop constraint [FK_CountryLanguage_Country]

drop table [dbo].[Country]

USE [Portalia]
GO
/****** Object:  Table [dbo].[Country]    Script Date: 1/13/2017 4:09:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Country](
	[ID] [varchar](3) NOT NULL,
	[Label] [varchar](128) NOT NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AD', N'Andorran')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AE', N'Emirian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AF', N'Afghan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AI', N'Antiguans')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AL', N'Albanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AM', N'Armenian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AO', N'Angolan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AR', N'Argentinean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AS', N'American')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AT', N'Austrian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AU', N'Australian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'AZ', N'Azerbaijani')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BA', N'Herzegovinian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BB', N'Barbadian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BD', N'Bangladeshi')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BE', N'Belgian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BF', N'Burkinabe')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BG', N'Bulgarian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BH', N'Bahraini')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BI', N'Burundian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BJ', N'Beninese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BN', N'Bruneian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BO', N'Bolivian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BR', N'Brazilian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BS', N'Bahamian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BT', N'Bhutanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BW', N'Motswana')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BY', N'Barbudans')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'BZ', N'Belizean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CA', N'Canadian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CD', N'Congolese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CF', N'Central African')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CH', N'Swiss')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CI', N'Ivorian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CL', N'Chilean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CM', N'Cameroonian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CN', N'Chinese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CO', N'Colombian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CR', N'Costa Rican')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CU', N'Cuban')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CV', N'Cape Verdean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CY', N'Cypriot')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'CZ', N'Czech')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'DE', N'German')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'DJ', N'Djibouti')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'DK', N'Danish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'DM', N'Dominican')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'DZ', N'Algerian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'EC', N'Ecuadorean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'EE', N'Estonian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'EG', N'Egyptian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ER', N'Eritrean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ES', N'Spanish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ET', N'Ethiopian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'FI', N'Finnish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'FJ', N'Fijian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'FM', N'Micronesian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'FR', N'French')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GA', N'Gabonese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GB', N'British')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GD', N'Grenadian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GE', N'Georgian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GH', N'Ghanaian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GM', N'Gambian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GN', N'Guinea-Bissauan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GQ', N'Equatorial Guinean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GR', N'Greek')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GT', N'Guatemalan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'GY', N'Guyanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'HN', N'Honduran')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'HR', N'Croatian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'HT', N'Haitian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'HU', N'Hungarian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ID', N'Indonesian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IE', N'Irish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IL', N'Israeli')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IN', N'Indian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IQ', N'Iraqi')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IR', N'Iranian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IS', N'Icelander')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'IT', N'Italian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'JM', N'Jamaican')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'JO', N'Jordanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'JP', N'Japanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KE', N'Kenyan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KG', N'Kyrgyz')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KH', N'Cambodian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KI', N'I-Kiribati')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KM', N'Comoran')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KP', N'North Korean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KR', N'South Korean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KW', N'Kuwaiti')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'KZ', N'Kazakhstani')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LA', N'Laotian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LB', N'Lebanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LC', N'Saint Lucian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LI', N'Liechtensteiner')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LK', N'Sri Lankan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LR', N'Liberian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LT', N'Lithuanian')
GO
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LU', N'Luxembourger')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LV', N'Latvian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'LY', N'Libyan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MA', N'Moroccan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MC', N'Monacan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MD', N'Moldovan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MG', N'Malagasy')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MH', N'Marshallese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MK', N'Macedonian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ML', N'Malian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MM', N'Burmese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MN', N'Mongolian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MR', N'Mauritanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MT', N'Maltese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MU', N'Mauritian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MV', N'Maldivan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MW', N'Malawian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MX', N'Mexican')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MY', N'Malaysian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'MZ', N'Mozambican')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NA', N'Namibian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NE', N'Nigerien')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NG', N'Nigerian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NI', N'Nicaraguan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NL', N'Dutch')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NO', N'Norwegian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NP', N'Nepalese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NR', N'Nauruan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'NZ', N'New Zealander')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'OM', N'Omani')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PA', N'Panamanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PE', N'Peruvian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PG', N'Papua New Guinean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PH', N'Filipino')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PK', N'Pakistani')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PL', N'Polish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PT', N'Portuguese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PW', N'Palauan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'PY', N'Paraguayan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'QA', N'Qatari')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'RO', N'Romanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'RS', N'Serbian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'RU', N'Russian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'RW', N'Rwandan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SA', N'Saudi')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SB', N'Solomon Islander')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SC', N'Seychellois')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SE', N'Swedish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SG', N'Singaporean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SI', N'Slovenian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SK', N'Slovakian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SL', N'Sierra Leonean')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SN', N'Senegalese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SO', N'Somali')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SR', N'Surinamer')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SS', N'Sudanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SV', N'Salvadoran')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SY', N'Syrian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'SZ', N'Swazi')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TD', N'Chadian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TG', N'Togolese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TH', N'Thai')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TJ', N'Tajik')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TN', N'Tunisian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TO', N'Tongan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TR', N'Turkish')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TT', N'Trinidadian or Tobagonian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TV', N'Tuvaluan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TW', N'Taiwanese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'TZ', N'Tanzanian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'UA', N'Ukrainian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'UG', N'Ugandan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'UY', N'Uruguayan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'UZ', N'Uzbekistani')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'VE', N'Venezuelan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'VN', N'Vietnamese')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'VU', N'Ni-Vanuatu')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'WS', N'Samoan')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'YE', N'Yemenite')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ZA', N'South African')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ZM', N'Zambian')
INSERT [dbo].[Country] ([ID], [Label]) VALUES (N'ZW', N'Zimbabwean')
