//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portalia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portalia.Resources.HomePage", typeof(HomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your profile picture.
        /// </summary>
        public static string ChangeProfilePicture {
            get {
                return ResourceManager.GetString("ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients &amp; Projects.
        /// </summary>
        public static string ClientAndProject {
            get {
                return ResourceManager.GetString("ClientAndProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA.
        /// </summary>
        public static string CRA {
            get {
                return ResourceManager.GetString("CRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNA.
        /// </summary>
        public static string DNA {
            get {
                return ResourceManager.GetString("DNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this 4 steps to start with your client.
        /// </summary>
        public static string FollowThis4 {
            get {
                return ResourceManager.GetString("FollowThis4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire expert consultants, freelancers for your online job.
        /// </summary>
        public static string HireExpertConsultants {
            get {
                return ResourceManager.GetString("HireExpertConsultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN US! TODAY.
        /// </summary>
        public static string JOINTUSTODAY {
            get {
                return ResourceManager.GetString("JOINTUSTODAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My personal space.
        /// </summary>
        public static string MyPersonalSpace {
            get {
                return ResourceManager.GetString("MyPersonalSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROJECTS!.
        /// </summary>
        public static string MyProject {
            get {
                return ResourceManager.GetString("MyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My user profile.
        /// </summary>
        public static string MyUserProfile {
            get {
                return ResourceManager.GetString("MyUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string NotesDeFrais {
            get {
                return ResourceManager.GetString("NotesDeFrais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your account and update your profile.
        /// </summary>
        public static string RegisterYourAccount {
            get {
                return ResourceManager.GetString("RegisterYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send proposal and waiting for approve.
        /// </summary>
        public static string SendPoposalAnd {
            get {
                return ResourceManager.GetString("SendPoposalAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN / SIGN UP.
        /// </summary>
        public static string SIGNINSIGNUP {
            get {
                return ResourceManager.GetString("SIGNINSIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        public static string SIGNOUT {
            get {
                return ResourceManager.GetString("SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0}.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best place to tell people why they are here.
        /// </summary>
        public static string TheBestPlace {
            get {
                return ResourceManager.GetString("TheBestPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference between involvement and commitment is like an eggs-and-ham breakfast:
        ///the chicken was involved; the pig was committed..
        /// </summary>
        public static string TheDifference {
            get {
                return ResourceManager.GetString("TheDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        public static string Timesheet {
            get {
                return ResourceManager.GetString("Timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your project documents.
        /// </summary>
        public static string UploadYourProject {
            get {
                return ResourceManager.GetString("UploadYourProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Portalia to turn the ideas into reality.
        /// </summary>
        public static string UsePortalia {
            get {
                return ResourceManager.GetString("UsePortalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account and update your profile.
        /// </summary>
        public static string YourAccountAndUpdateYourProfile {
            get {
                return ResourceManager.GetString("YourAccountAndUpdateYourProfile", resourceCulture);
            }
        }
    }
}
