//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portalia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nationality {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nationality() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portalia.Resources.Nationality", typeof(Nationality).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorran.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirian.
        /// </summary>
        public static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghan.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antigua and Barbuda.
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiguans.
        /// </summary>
        public static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angolan.
        /// </summary>
        public static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antarctica.
        /// </summary>
        public static string AQ {
            get {
                return ResourceManager.GetString("AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentinean.
        /// </summary>
        public static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austrian.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian.
        /// </summary>
        public static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aruba.
        /// </summary>
        public static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzegovinian.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbadian.
        /// </summary>
        public static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangladeshi.
        /// </summary>
        public static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgian.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burkinabe.
        /// </summary>
        public static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahraini.
        /// </summary>
        public static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burundian.
        /// </summary>
        public static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beninese.
        /// </summary>
        public static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Barthelemy.
        /// </summary>
        public static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bermuda.
        /// </summary>
        public static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruneian.
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivian.
        /// </summary>
        public static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahamian.
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bhutanese.
        /// </summary>
        public static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouvet Island.
        /// </summary>
        public static string BV {
            get {
                return ResourceManager.GetString("BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motswana.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbudans.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belizean.
        /// </summary>
        public static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocos (Keeling) Islands.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congolese.
        /// </summary>
        public static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central African.
        /// </summary>
        public static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congo.
        /// </summary>
        public static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivorian.
        /// </summary>
        public static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Islands.
        /// </summary>
        public static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilean.
        /// </summary>
        public static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cameroonian.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rican.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuban.
        /// </summary>
        public static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cape Verdean.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Island.
        /// </summary>
        public static string CX {
            get {
                return ResourceManager.GetString("CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cypriot.
        /// </summary>
        public static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djibouti.
        /// </summary>
        public static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican.
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominican Republic.
        /// </summary>
        public static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algerian.
        /// </summary>
        public static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecuadorean.
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyptian.
        /// </summary>
        public static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Sahara.
        /// </summary>
        public static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eritrean.
        /// </summary>
        public static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethiopian.
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fijian.
        /// </summary>
        public static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falkland Islands (Malvinas).
        /// </summary>
        public static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronesian.
        /// </summary>
        public static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        public static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabonese.
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenadian.
        /// </summary>
        public static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Guiana.
        /// </summary>
        public static string GF {
            get {
                return ResourceManager.GetString("GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guernsey.
        /// </summary>
        public static string GG {
            get {
                return ResourceManager.GetString("GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghanaian.
        /// </summary>
        public static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibraltar.
        /// </summary>
        public static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenland.
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambian.
        /// </summary>
        public static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissauan.
        /// </summary>
        public static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guadeloupe.
        /// </summary>
        public static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial Guinean.
        /// </summary>
        public static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Georgia and the South Sandwich Islands.
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guatemalan.
        /// </summary>
        public static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guam.
        /// </summary>
        public static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea-Bissau.
        /// </summary>
        public static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guyanese.
        /// </summary>
        public static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        public static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honduran.
        /// </summary>
        public static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haitian.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli.
        /// </summary>
        public static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian.
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraqi.
        /// </summary>
        public static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iranian.
        /// </summary>
        public static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelander.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican.
        /// </summary>
        public static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jordanian.
        /// </summary>
        public static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenyan.
        /// </summary>
        public static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        public static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodian.
        /// </summary>
        public static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I-Kiribati.
        /// </summary>
        public static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comoran.
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Korean.
        /// </summary>
        public static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korean.
        /// </summary>
        public static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuwaiti.
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakhstani.
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laotian.
        /// </summary>
        public static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese.
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Lucian.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liechtensteiner.
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sri Lankan.
        /// </summary>
        public static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberian.
        /// </summary>
        public static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourger.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libyan.
        /// </summary>
        public static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroccan.
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monacan.
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moldovan.
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malagasy.
        /// </summary>
        public static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshallese.
        /// </summary>
        public static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malian.
        /// </summary>
        public static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritanian.
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritian.
        /// </summary>
        public static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maldivan.
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malawian.
        /// </summary>
        public static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican.
        /// </summary>
        public static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        public static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozambican.
        /// </summary>
        public static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibian.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerien.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian.
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicaraguan.
        /// </summary>
        public static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepalese.
        /// </summary>
        public static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauruan.
        /// </summary>
        public static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealander.
        /// </summary>
        public static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omani.
        /// </summary>
        public static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panamanian.
        /// </summary>
        public static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruvian.
        /// </summary>
        public static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papua New Guinean.
        /// </summary>
        public static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistani.
        /// </summary>
        public static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palauan.
        /// </summary>
        public static string PW {
            get {
                return ResourceManager.GetString("PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguayan.
        /// </summary>
        public static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qatari.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rwandan.
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solomon Islander.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seychellois.
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singaporean.
        /// </summary>
        public static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakian.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sierra Leonean.
        /// </summary>
        public static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senegalese.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somali.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surinamer.
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudanese.
        /// </summary>
        public static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvadoran.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrian.
        /// </summary>
        public static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swazi.
        /// </summary>
        public static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chadian.
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Togolese.
        /// </summary>
        public static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajik.
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisian.
        /// </summary>
        public static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongan.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinidadian or Tobagonian.
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvaluan.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwanese.
        /// </summary>
        public static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzanian.
        /// </summary>
        public static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugandan.
        /// </summary>
        public static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguayan.
        /// </summary>
        public static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistani.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venezuelan.
        /// </summary>
        public static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni-Vanuatu.
        /// </summary>
        public static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samoan.
        /// </summary>
        public static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemenite.
        /// </summary>
        public static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African.
        /// </summary>
        public static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zambian.
        /// </summary>
        public static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zimbabwean.
        /// </summary>
        public static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
