//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portalia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Proposal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Proposal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portalia.Resources.Proposal", typeof(Proposal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity report.
        /// </summary>
        public static string ActivityReport {
            get {
                return ResourceManager.GetString("ActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and upload it.
        /// </summary>
        public static string AndUploadIt {
            get {
                return ResourceManager.GetString("AndUploadIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients &amp; Projects.
        /// </summary>
        public static string ClientsProjects {
            get {
                return ResourceManager.GetString("ClientsProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Document.
        /// </summary>
        public static string CreateNewDocument {
            get {
                return ResourceManager.GetString("CreateNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Document.
        /// </summary>
        public static string DownLoadDocument {
            get {
                return ResourceManager.GetString("DownLoadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here to upload.
        /// </summary>
        public static string Dropfilesheretoupload {
            get {
                return ResourceManager.GetString("Dropfilesheretoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of contract bonuses.
        /// </summary>
        public static string EndOfContractBonuses {
            get {
                return ResourceManager.GetString("EndOfContractBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My client recovery.
        /// </summary>
        public static string MyClientRecovery {
            get {
                return ResourceManager.GetString("MyClientRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes contrats.
        /// </summary>
        public static string Mycontracts {
            get {
                return ResourceManager.GetString("Mycontracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My end of contract documents.
        /// </summary>
        public static string MyEndOfContractDocuments {
            get {
                return ResourceManager.GetString("MyEndOfContractDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My invoices.
        /// </summary>
        public static string MyInvoices {
            get {
                return ResourceManager.GetString("MyInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My opportunities.
        /// </summary>
        public static string MyOpportunities {
            get {
                return ResourceManager.GetString("MyOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My pay slip.
        /// </summary>
        public static string MyPaySlip {
            get {
                return ResourceManager.GetString("MyPaySlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProject {
            get {
                return ResourceManager.GetString("MyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Proposal.
        /// </summary>
        public static string NewProposal {
            get {
                return ResourceManager.GetString("NewProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the.
        /// </summary>
        public static string PleaseFillIn {
            get {
                return ResourceManager.GetString("PleaseFillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your document before send.
        /// </summary>
        public static string PleaseUploadYourDocumentBeforeSend {
            get {
                return ResourceManager.GetString("PleaseUploadYourDocumentBeforeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Project Now.
        /// </summary>
        public static string PostProjectNow {
            get {
                return ResourceManager.GetString("PostProjectNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project template document.
        /// </summary>
        public static string ProjectTemplateDocument {
            get {
                return ResourceManager.GetString("ProjectTemplateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal ID.
        /// </summary>
        public static string ProposalID {
            get {
                return ResourceManager.GetString("ProposalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My project.
        /// </summary>
        public static string ProposalMyProject {
            get {
                return ResourceManager.GetString("ProposalMyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve account.
        /// </summary>
        public static string ResearveAccount {
            get {
                return ResourceManager.GetString("ResearveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Proposal.
        /// </summary>
        public static string SendProposal {
            get {
                return ResourceManager.GetString("SendProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Proposal.
        /// </summary>
        public static string SentProposal {
            get {
                return ResourceManager.GetString("SentProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0}.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more detail you provide, the better chance you have in getting exactly
        ///                                  what you are after in the shortest possible time period..
        /// </summary>
        public static string TheMoreDetail {
            get {
                return ResourceManager.GetString("TheMoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your description here....
        /// </summary>
        public static string TypeYourDescription {
            get {
                return ResourceManager.GetString("TypeYourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Your Profile.
        /// </summary>
        public static string UpdateYourProfile {
            get {
                return ResourceManager.GetString("UpdateYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document.
        /// </summary>
        public static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’d love to hear from you. Interested in working together? Fill out the form below with some info about your project and I will get back to you as soon as I can. Please allow a couple days for me to respond..
        /// </summary>
        public static string Wedlovetohearfromyou {
            get {
                return ResourceManager.GetString("Wedlovetohearfromyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proposal cannot be sent. You can work only on one proposal at the same time!.
        /// </summary>
        public static string youareworkinginthisproject {
            get {
                return ResourceManager.GetString("youareworkinginthisproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project name is important as it is what attracts freelancers to bid on your project.
        ///                                You should clearly describe what you need in as few words as possible..
        /// </summary>
        public static string YourClientName {
            get {
                return ResourceManager.GetString("YourClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile look good!.
        /// </summary>
        public static string YourProfileLookGood {
            get {
                return ResourceManager.GetString("YourProfileLookGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project name is important as it is what attracts freelancers to bid on your project.
        ///                                You should clearly describe what you need in as few words as possible..
        /// </summary>
        public static string YourProjectNameIs {
            get {
                return ResourceManager.GetString("YourProjectNameIs", resourceCulture);
            }
        }
    }
}
