USE [Portalia]
GO

--Daily basic
INSERT INTO RefData (Code, [Key],[Value])
VALUES ('DailyBasic','2','Par jour')
GO
INSERT INTO RefData (Code, [Key],[Value])
VALUES ('DailyBasic','3','Par mois')
GO
INSERT INTO RefData (Code, [Key],[Value])
VALUES ('DailyBasic','5','Par ans')
GO

--Title
--Daily basic
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Title','M.','M.')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Title','Mme.','Mme.')

--Currency
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AED','United Arab Emirates dirham')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AFN','Afghan afghani')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ALL','Albanian lek')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AMD','Armenian dram')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ANG','Netherlands Antillean guilder')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AOA','Angolan kwanza')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ARS','Argentine peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AUD','Australian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AWG','Aruban florin')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','AZN','Azerbaijani manat')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BAM','Bosnia and Herzegovina convertible mark')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BBD','Barbados dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BDT','Bangladeshi taka')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BGN','Bulgarian lev')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BHD','Bahraini dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BIF','Burundian franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BMD','Bermudian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BND','Brunei dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BOB','Boliviano')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BOV','Bolivian Mvdol')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BRL','Brazilian real')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BSD','Bahamian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BTN','Bhutanese ngultrum')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BWP','Botswana pula')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BYN','Belarusian ruble')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BYR','Belarusian ruble')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','BZD','Belize dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CAD','Canadian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CDF','Congolese franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CHE','WIR Euro')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CHF','Swiss Franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CHW','WIR Franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CLF','Unidad de Fomento')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CLP','Chilean peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CNY','Chinese yuan')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','COP','Colombian peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','COU','Unidad de Valor Real')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CRC','Costa Rican colon')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CUC','Cuban convertible peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CUP','Cuban peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CVE','Cape Verde escudo')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','CZK','Czech Koruna')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','DJF','Djiboutian franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','DKK','Danish krone')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','DOP','Dominican peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','DZD','Algerian dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','EGP','Egyptian pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ERN','Eritrean nakfa')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ETB','Ethiopian birr')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','EUR','Euro')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','FJD','Fiji dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','FKP','Falkland Islands pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GBP','Pound sterling')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GEL','Georgian lari')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GHS','Ghanaian cedi')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GIP','Gibraltar pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GMD','Gambian dalasi')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GNF','Guinean franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GTQ','Guatemalan quetzal')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','GYD','Guyanese dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','HKD','Hong Kong dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','HNL','Honduran lempira')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','HRK','Croatian kuna')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','HTG','Haitianurde')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','HUF','Hungarian forint')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','IDR','Indonesian rupiah')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ILS','Israeli new shekel')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','INR','Indian Rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','IQD','Iraqi dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','IRR','Iranian rial')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ISK','Icelandic króna')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','JMD','Jamaican dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','JOD','Jordanian dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','JPY','Japanese yen')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KES','Kenyan shilling')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KGS','Kyrgyzstani som')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KHR','Cambodian riel')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KMF','Comoro franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KPW','North Korean won')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KRW','South Korean won')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KWD','Kuwaiti dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KYD','Cayman Islands dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','KZT','Kazakhstani tenge')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LAK','Lao kip')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LBP','Lebanese pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LKR','Sri Lankan rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LRD','Liberian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LSL','Lesotho loti')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LTL','Lithuanian litas')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LVL','Latvian lats')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','LYD','Libyan dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MAD','Moroccan dirham')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MDL','Moldovan leu')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MGA','Malagasy ariary')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MKD','Macedonian denar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MMK','Myanma kyat')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MNT','Mongolian tugrik')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MOP','Macanese pataca')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MRO','Mauritanian ouguiya')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MUR','Mauritian rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MVR','Maldivian rufiyaa')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MWK','Malawian kwacha')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MXN','Mexican Peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MXV','Mexican Unidad de Inversion (UDI) ')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MYR','Malaysian ringgit')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','MZN','Mozambican metical')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NAD','Namibian dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NGN','Nigerian naira')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NIO','Nicaraguan córdoba')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NOK','Norwegian krone')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NPR','Nepalese rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','NZD','New Zealand dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','OMR','Omani rial')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PAB','Panamanian balboa')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PEN','Peruvian nuevo sol')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PGK','Papua New Guinean kina')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PHP','Philippine peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PKR','Pakistani rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PLN','Polish zloty')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','PYG','Paraguayan guaraní')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','QAR','Qatari riyal')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','RON','Romanian new leu')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','RSD','Serbian dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','RUB','Russian rouble')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','RWF','Rwandan franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SAR','Saudi riyal')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SBD','Solomon Islands dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SCR','Seychelles rupee')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SDG','Sudanese pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SEK','Swedish krona/kronor')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SGD','Singapore dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SHP','Saint Helena pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SLL','Sierra Leonean leone')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SOS','Somali shilling')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SRD','Surinamese dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SSP','South Sudanese pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','STD','São Tomé and Príncipe dobra')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SYP','Syrian pound')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','SZL','Swazi lilangeni')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','THB','Thai baht')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TJS','Tajikistani somoni')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TMT','Turkmenistani manat')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TND','Tunisian dinar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TOP','Tongan pa?anga')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TRY','Turkish lira')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TTD','Trinidad and Tobago dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TWD','New Taiwan dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','TZS','Tanzanian shilling')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','UAH','Ukrainian hryvnia')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','UGX','Ugandan shilling')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','USD','United States Dollars')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','USN','United States dollar (next day)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','USS','United States dollar (same day)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','UYI','Uruguay Peso en Unidades Indexadas (URUIURUI)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','UYU','Uruguayan peso')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','UZS','Uzbekistan som')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','VEF','Venezuelan bolívar fuerte')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','VND','Vietnamese dong')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','VUV','Vanuatu vatu')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','WST','Samoan tala')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XAF','CFA franc BEAC')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XAG','Silver')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XAU','Gold')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XBA','European Composite Unit (EURCO)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XBB','European Monetary Unit (E.M.U.-6)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XBC','European Unit of Account 9 (E.U.A.-9)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XBD','European Unit of Account 17 (E.U.A.-17)')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XCD','East Caribbean dollar')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XDR','Special drawing rights')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XFU','UIC franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XOF','CFA franc BCEAO')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XPD','Palladium')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XPF','CFP franc')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XPT','Platinum')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XTS','Code reserved for testing purposes')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','XXX','No currency')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','YER','Yemeni rial')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ZAR','South African rand')
INSERT INTO RefData (Code, [Key],[Value]) VALUES ('Currency','ZMW','Zambian kwacha')

